### PR TITLE
[1.19] Improve duplicate checks for implicit counts of 1

### LINKED ISSUE #27: duplication check doesn't handle omitted count of 1
### Version

v1.19.2-0.3.0

### Describe the bug!

When you have two recipes where you have an output on one item and one of the recipes omits the count of 1 and the other doesn't, they won't be detected as duplicates.

### Crash Report

_No response_

### Log

_No response_

### Additional Context

No

### Modifications

_No response_

### Did the issue happen in singleplayer or on a server?

Both

### PR DESCRIPTION
**Pull request by rlnt**
The sanitizing was initially applied to all possible elements but this obviously drastically increased load times.
I did some benchmarking on the dev version of Enigmatica 9 with EE. Here are the results.

Old version (no implicit count checks):
8.853ms

New version (sanitized every element):
18.330ms

With basic type filter:
17.273ms
```java
if (firstElem.getClass() == secondElem.getClass() ||
    (firstElem instanceof JsonPrimitive && secondElem instanceof JsonObject) ||
    (firstElem instanceof JsonObject && secondElem instanceof JsonPrimitive)) {
    firstElem = sanitize(firstElem);
    secondElem = sanitize(secondElem);
}
```

With basic type filter and array length checks:
17.068ms
```java
if ((firstElem instanceof JsonArray firstArray && secondElem instanceof JsonArray secondArray &&
     firstArray.size() == secondArray.size()) ||
    firstElem.getClass() == secondElem.getClass() ||
    (firstElem instanceof JsonPrimitive && secondElem instanceof JsonObject) ||
    (firstElem instanceof JsonObject && secondElem instanceof JsonPrimitive)) {
    firstElem = sanitize(firstElem);
    secondElem = sanitize(secondElem);
}
```

With type filter, array length checks and without primitives:
14.593ms
```java
if ((firstElem instanceof JsonArray firstArray && secondElem instanceof JsonArray secondArray &&
     firstArray.size() == secondArray.size()) ||
    (firstElem instanceof JsonObject && secondElem instanceof JsonObject) ||
    (firstElem instanceof JsonPrimitive && secondElem instanceof JsonObject) ||
    (firstElem instanceof JsonObject && secondElem instanceof JsonPrimitive)) {
    firstElem = sanitize(firstElem);
    secondElem = sanitize(secondElem);
}
```

The last method has an insanely ugly condition but it's only 5.740ms slower than the version without any sanitizing and implicit count checks at all.

### CODE REVIEW

File: Common/src/main/java/com/almostreliable/unified/utils/JsonCompare.java [hunk 1]
```diff
@@ -101,14 +103,104 @@ public static boolean matches(JsonObject first, JsonObject second, Collection<St
...
         for (String firstKey : firstValidKeys) {
-            if (!first.get(firstKey).equals(second.get(firstKey))) {
+            JsonElement firstElem = first.get(firstKey);
+            JsonElement secondElem = second.get(firstKey);
+
+            // the second element can still be null although the valid keys have the same size
+            if (secondElem == null) return false;
+
+            // sanitize elements for implicit counts of 1
+            if ((firstElem instanceof JsonArray firstArray && secondElem instanceof JsonArray secondArray &&
```
Comment (LLytho) [inline Common/src/main/java/com/almostreliable/unified/utils/JsonCompare.java]: extract if condition into own method or sub methods. Also include javadoc the the extracted method to explain why it's needed

File: Common/src/main/java/com/almostreliable/unified/utils/JsonCompare.java [hunk 2]
```diff
@@ -101,14 +103,104 @@ public static boolean matches(JsonObject first, JsonObject second, Collection<St
...
+            var sanitized = createSanitizedObjectOrDefault(jsonObject.get(key), jsonObject);
+
+            // ensure the object changed (was sanitized) and that we got a JsonObject
+            //noinspection ObjectEquality
+            if (sanitized == jsonObject || !(sanitized instanceof JsonObject sanitizedObject)) {
+                return jsonObject;
+            }
+
+            // add all other properties from the original object
+            for (var entry : jsonObject.entrySet()) {
```
Comment (LLytho) [inline Common/src/main/java/com/almostreliable/unified/utils/JsonCompare.java]: Why this part exist? Isn't it just a shallow copy?

Comment (rlnt) [reply Common/src/main/java/com/almostreliable/unified/utils/JsonCompare.java]: The object stored in `sanitized` only has the value passed to `createSanitizedObjectOrDefault` under the `au_sanitizied` key and the count of 1.
In order to successfully compare them after the transformation, the other properties need to be applied too, otherwise, you'd lose information.

I will extract it as a method, call it `merge`, and add some documentation.

**Review by LLytho — APPROVED** [review]
